[package]
name = "pdk-experiments"
version = "0.1.0"
edition = "2018"

[dependencies]
dynamic-simple = { path = "dynamic-simple", version = "0.1.0" }
wasm-simple = { path = "wasm-simple", version = "0.1.0" }
