[package]
name = "abi-stable-connectors"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
abi_stable = { version = "0.10", default-features = false }
common-abi-stable-connectors = { path = "common", version = "0.1.0" }
tokio = { version = "1.12", features = ["full"] }
