[package]
name = "abi-stable-connectors"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
abi_stable = "0.10"
common-abi-stable-connectors = { path = "common", version = "0.1.0" }
