[package]
name = "native-codec"
version = "0.1.0"
edition = "2018"

[dependencies]
common-ncodec = { path = "common", version = "0.1.0" }
plugin-sample-ncodec = { path = "plugin-sample", version = "0.1.0" }
