[package]
name = "common-abi-stable-connectors"
version = "0.1.0"
edition = "2018"

[dependencies]
abi_stable = { version = "0.10", default-features = false }
tokio = { version = "1.12", features = ["full"] }
